name: バグ修正
description: バグ修正するとき用
title: "bugfix: "
labels: ["bug"]
body:
  - type: markdown
    id: description
    attributes:
      label: バグの内容
  - type: markdown
    id: expected-action
    attributes:
      label: 期待される動作
  - type: dropdown
    id: env-device
    attributes:
      label: 環境(ハード)
      multiple: false
      options:
        - PC
        - スマホ(開発者モード使用でもよし)
